from typing import TypeVar, Callable, overload

A = TypeVar('A')
B = TypeVar('B')
C = TypeVar('C')
D = TypeVar('D')
E = TypeVar('E')
F = TypeVar('F')
G = TypeVar('G')
H = TypeVar('H')
T = TypeVar('T')

# pipe overloads
@overload
def pipe(value: A, f1: Callable[[A], B], /) -> B: ...
@overload
def pipe(value: A, f1: Callable[[A], B], f2: Callable[[B], C], /) -> C: ...
@overload
def pipe(value: A, f1: Callable[[A], B], f2: Callable[[B], C], f3: Callable[[C], D], /) -> D: ...
@overload
def pipe(value: A, f1: Callable[[A], B], f2: Callable[[B], C], f3: Callable[[C], D], f4: Callable[[D], E], /) -> E: ...
@overload
def pipe(value: A, f1: Callable[[A], B], f2: Callable[[B], C], f3: Callable[[C], D], f4: Callable[[D], E], f5: Callable[[E], F], /) -> F: ...
@overload
def pipe(value: A, f1: Callable[[A], B], f2: Callable[[B], C], f3: Callable[[C], D], f4: Callable[[D], E], f5: Callable[[E], F], f6: Callable[[F], G], /) -> G: ...
@overload
def pipe(value: A, f1: Callable[[A], B], f2: Callable[[B], C], f3: Callable[[C], D], f4: Callable[[D], E], f5: Callable[[E], F], f6: Callable[[F], G], f7: Callable[[G], H], /) -> H: ...
def pipe(value: object, /, *funcs: Callable) -> object: ...

# compose overloads
@overload
def compose(f1: Callable[[A], B], /) -> Callable[[A], B]: ...
@overload
def compose(f1: Callable[[B], C], f2: Callable[[A], B], /) -> Callable[[A], C]: ...
@overload
def compose(f1: Callable[[C], D], f2: Callable[[B], C], f3: Callable[[A], B], /) -> Callable[[A], D]: ...
@overload
def compose(f1: Callable[[D], E], f2: Callable[[C], D], f3: Callable[[B], C], f4: Callable[[A], B], /) -> Callable[[A], E]: ...
def compose(*funcs: Callable) -> Callable: ...

# first_some
@overload
def first_some(f1: Callable[..., T | None], /) -> Callable[..., T | None]: ...
@overload
def first_some(f1: Callable[..., T | None], f2: Callable[..., T | None], /) -> Callable[..., T | None]: ...
@overload
def first_some(f1: Callable[..., T | None], f2: Callable[..., T | None], f3: Callable[..., T | None], /) -> Callable[..., T | None]: ...
@overload
def first_some(f1: Callable[..., T | None], f2: Callable[..., T | None], f3: Callable[..., T | None], f4: Callable[..., T | None], /) -> Callable[..., T | None]: ...
def first_some(*funcs: Callable[..., T | None]) -> Callable[..., T | None]: ...

# pipeline overloads (same as pipe but returns callable)
@overload
def pipeline(f1: Callable[[A], B], /) -> Callable[[A], B]: ...
@overload
def pipeline(f1: Callable[..., A], f2: Callable[[A], B], /) -> Callable[..., B]: ...
@overload
def pipeline(f1: Callable[..., A], f2: Callable[[A], B], f3: Callable[[B], C], /) -> Callable[..., C]: ...
@overload
def pipeline(f1: Callable[..., A], f2: Callable[[A], B], f3: Callable[[B], C], f4: Callable[[C], D], /) -> Callable[..., D]: ...
def pipeline(*funcs: Callable) -> Callable: ...
