from collections.abc import Callable
from typing import Any, Generic, TypeVar, overload

A = TypeVar('A')
B = TypeVar('B')
C = TypeVar('C')
D = TypeVar('D')
E = TypeVar('E')
F = TypeVar('F')
G = TypeVar('G')
H = TypeVar('H')
T = TypeVar('T')
E2 = TypeVar('E2')


class Result(Generic[T, E]):
    def is_ok(self) -> bool: ...
    def is_err(self) -> bool: ...
    def unwrap(self) -> T: ...
    def unwrap_or(self, default: T) -> T: ...
    def unwrap_err(self) -> E: ...
    def map(self, f: Callable[[T], B]) -> Result[B, E]: ...
    def map_err(self, f: Callable[[E], E2]) -> Result[T, E2]: ...
    def and_then(self, f: Callable[[T], Result[B, E]]) -> Result[B, E]: ...
    def or_else(self, f: Callable[[E], Result[T, E2]]) -> Result[T, E2]: ...
    def __bool__(self) -> bool: ...


class Ok(Result[T, E]):
    value: T
    def __init__(self, value: T) -> None: ...


class Err(Result[T, E]):
    error: E
    def __init__(self, error: E) -> None: ...

# pipe overloads
@overload
def pipe(value: A, f1: Callable[[A], B], /) -> B: ...
@overload
def pipe(value: A, f1: Callable[[A], B], f2: Callable[[B], C], /) -> C: ...
@overload
def pipe(value: A, f1: Callable[[A], B], f2: Callable[[B], C], f3: Callable[[C], D], /) -> D: ...
@overload
def pipe(value: A, f1: Callable[[A], B], f2: Callable[[B], C], f3: Callable[[C], D], f4: Callable[[D], E], /) -> E: ...
@overload
def pipe(value: A, f1: Callable[[A], B], f2: Callable[[B], C], f3: Callable[[C], D], f4: Callable[[D], E], f5: Callable[[E], F], /) -> F: ...
@overload
def pipe(value: A, f1: Callable[[A], B], f2: Callable[[B], C], f3: Callable[[C], D], f4: Callable[[D], E], f5: Callable[[E], F], f6: Callable[[F], G], /) -> G: ...
@overload
def pipe(value: A, f1: Callable[[A], B], f2: Callable[[B], C], f3: Callable[[C], D], f4: Callable[[D], E], f5: Callable[[E], F], f6: Callable[[F], G], f7: Callable[[G], H], /) -> H: ...
@overload
def pipe(value: A, /) -> A: ...
@overload
def pipe(value: object, /, *funcs: Callable[..., object]) -> object: ...

# compose overloads
@overload
def compose(f1: Callable[[A], B], /) -> Callable[[A], B]: ...
@overload
def compose(f1: Callable[[B], C], f2: Callable[[A], B], /) -> Callable[[A], C]: ...
@overload
def compose(f1: Callable[[C], D], f2: Callable[[B], C], f3: Callable[[A], B], /) -> Callable[[A], D]: ...
@overload
def compose(f1: Callable[[D], E], f2: Callable[[C], D], f3: Callable[[B], C], f4: Callable[[A], B], /) -> Callable[[A], E]: ...
@overload
def compose(*funcs: Callable[..., object]) -> Callable[..., object]: ...

# first_some
@overload
def first_some(f1: Callable[..., T | None], /) -> Callable[..., T | None]: ...
@overload
def first_some(f1: Callable[..., T | None], f2: Callable[..., T | None], /) -> Callable[..., T | None]: ...
@overload
def first_some(f1: Callable[..., T | None], f2: Callable[..., T | None], f3: Callable[..., T | None], /) -> Callable[..., T | None]: ...
@overload
def first_some(f1: Callable[..., T | None], f2: Callable[..., T | None], f3: Callable[..., T | None], f4: Callable[..., T | None], /) -> Callable[..., T | None]: ...
@overload
def first_some(*funcs: Callable[..., T | None]) -> Callable[..., T | None]: ...

# pipeline overloads (same as pipe but returns callable)
@overload
def pipeline(f1: Callable[[A], B], /) -> Callable[[A], B]: ...
@overload
def pipeline(f1: Callable[..., A], f2: Callable[[A], B], /) -> Callable[..., B]: ...
@overload
def pipeline(f1: Callable[..., A], f2: Callable[[A], B], f3: Callable[[B], C], /) -> Callable[..., C]: ...
@overload
def pipeline(f1: Callable[..., A], f2: Callable[[A], B], f3: Callable[[B], C], f4: Callable[[C], D], /) -> Callable[..., D]: ...
@overload
def pipeline(*funcs: Callable[..., object]) -> Callable[..., object]: ...


@overload
async def async_pipe(value: A, /) -> A: ...
@overload
async def async_pipe(value: object, /, *funcs: Callable[..., object]) -> object: ...
def try_pipe(value: object, /, *funcs: Callable[..., object]) -> Result[Any, Exception]: ...
async def async_try_pipe(value: object, /, *funcs: Callable[..., object]) -> Result[Any, Exception]: ...
