"""Type stubs for PersistentMap."""
from __future__ import annotations

import collections.abc
from typing import Generic, Iterator, Mapping, TypeVar, overload

K = TypeVar('K')
V = TypeVar('V')
D = TypeVar('D')


class PersistentMap(Generic[K, V], Mapping[K, V]):
    """Immutable mapping with structural sharing."""

    def __init__(self, _root: object = ..., _count: int = ..., /, **kwargs: V) -> None: ...

    @classmethod
    def from_dict(cls, d: dict[K, V]) -> PersistentMap[K, V]: ...

    def set(self, key: K, value: V) -> PersistentMap[K, V]: ...

    def delete(self, key: K) -> PersistentMap[K, V]: ...

    @overload
    def get(self, key: K) -> V | None: ...
    @overload
    def get(self, key: K, default: V) -> V: ...
    @overload
    def get(self, key: K, default: D) -> V | D: ...

    def __getitem__(self, key: K) -> V: ...

    def __contains__(self, key: object) -> bool: ...

    def __len__(self) -> int: ...

    def __iter__(self) -> Iterator[K]: ...

    def __hash__(self) -> int: ...

    def __eq__(self, other: object) -> bool: ...

    def __repr__(self) -> str: ...

    def transient(self) -> TransientMap[K, V]: ...


class TransientMap(Generic[K, V]):
    """Mutable builder for PersistentMap, used for batch construction."""

    def __setitem__(self, key: K, value: V) -> None: ...

    def __delitem__(self, key: K) -> None: ...

    def __getitem__(self, key: K) -> V: ...

    def __contains__(self, key: object) -> bool: ...

    def __len__(self) -> int: ...

    def persistent(self) -> PersistentMap[K, V]: ...

    def __enter__(self) -> TransientMap[K, V]: ...

    def __exit__(self, *args: object) -> None: ...
