"""Type stubs for PersistentSet."""
from __future__ import annotations

import collections.abc
from typing import Any, Generic, Iterator, TypeVar

T = TypeVar('T')
S = TypeVar('S')


class PersistentSet(Generic[T], collections.abc.Set[T]):
    """Immutable set with structural sharing."""

    def __init__(self, iterable: object | None = ...) -> None: ...

    @classmethod
    def _make(cls, root: object, count: int) -> PersistentSet[T]: ...

    def add(self, elem: T) -> PersistentSet[T]: ...

    def discard(self, elem: T) -> PersistentSet[T]: ...

    def __contains__(self, elem: object) -> bool: ...

    def __len__(self) -> int: ...

    def __iter__(self) -> Iterator[T]: ...

    def __and__(self, other: collections.abc.Iterable[S]) -> PersistentSet[T]: ...

    def __or__(self, other: collections.abc.Iterable[S]) -> PersistentSet[T | S]: ...

    def __sub__(self, other: collections.abc.Iterable[Any]) -> PersistentSet[T]: ...

    def __xor__(self, other: collections.abc.Iterable[S]) -> PersistentSet[T | S]: ...

    def issubset(self, other: collections.abc.Set[Any]) -> bool: ...

    def issuperset(self, other: collections.abc.Set[Any]) -> bool: ...

    def __hash__(self) -> int: ...

    def __eq__(self, other: object) -> bool: ...

    def __repr__(self) -> str: ...
