"""Type stubs for PersistentVector."""
from __future__ import annotations

import collections.abc
from typing import Generic, Iterator, Sequence, TypeVar, overload

T = TypeVar('T')


class PersistentVector(Generic[T], Sequence[T]):
    """Immutable vector with structural sharing."""

    def __init__(self, iterable: object | None = ...) -> None: ...

    def append(self, value: T) -> PersistentVector[T]: ...

    def set(self, index: int, value: T) -> PersistentVector[T]: ...

    @overload
    def __getitem__(self, index: int) -> T: ...
    @overload
    def __getitem__(self, index: slice) -> PersistentVector[T]: ...

    def __len__(self) -> int: ...

    def __iter__(self) -> Iterator[T]: ...

    def __hash__(self) -> int: ...

    def __eq__(self, other: object) -> bool: ...

    def __add__(self, other: PersistentVector[T] | list[T] | tuple[T, ...]) -> PersistentVector[T]: ...

    def __repr__(self) -> str: ...
